### ISSUE TITLE
Error "Unknown Script  TTS Failed" 

### ISSUE THREAD

**Issue by underboob420** [techitapart/rpan_chat_commands#1]
every time I run the !tts command followed by my text I get this error in logs.

**Comment by techitapart** [comment]
Sorry for the bug. Solution is [here](https://stackoverflow.com/questions/64765243/how-to-solve-valueerror-unable-to-find-token-seed-did-https-translate-google). I was able to replicate the issue and upgrading gtts solved it for me. Let me know if you need anything else
